version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      main-net:
        aliases:
          - redis

  historica:
    image: historica
    ipc: host
    networks:
      main-net:
        aliases:
          - historica
    volumes:
      - shared-files:/app/files
      - cache-volume:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llm:
    image: llm
    ipc: host
    networks:
      main-net:
        aliases:
          - llm
    volumes:
      - shared-files:/app/files
      - cache-volume:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]

  speech:
    image: speech
    ipc: host
    networks:
      main-net:
        aliases:
          - speech
    volumes:
      - shared-files:/app/files
      - cache-volume:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  wav2lip:
    image: wav2lip
    ipc: host
    networks:
      main-net:
        aliases:
          - wav2lip
    volumes:
      - shared-files:/app/files
      - cache-volume:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu] 

  worker:
    image: worker
    environment:
      - CONFIG_DIR=""
    ports:
      - "3000:3000"
    ipc: host
    depends_on:
      - llm
    networks:
      main-net:
        aliases:
          - worker
    volumes:
      - shared-files:/app/files
      - cache-volume:/app/cache

  web:
    image: web2
    ports:
      - 3000
    ipc: host
    networks:
      main-net:
        aliases:
          - web

networks:
  main-net:

volumes:
  shared-files:
  cache-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fragro/Development/cache
