version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      main-net:
        aliases:
          - redis 
  llm:
    image: llm
    ports:
      - "3002:3002"
    ipc: host
    networks:
      main-net:
        aliases:
          - llm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  speech:
    image: speech
    ports:
      - "3003:3003"
    ipc: host
    networks:
      main-net:
        aliases:
          - speech
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  worker:
    image: worker
    environment:
      - CONFIG_DIR=""
    ports:
      - "3000:3000"
    ipc: host
    depends_on:
      - llm
    networks:
      main-net:
        aliases:
          - worker

networks:
  main-net: