from typing import Protocol, Optional

class KeyGeneratorProtocol(Protocol):
    def __init__(self, collection: str): ...
    def _generate_key(self) -> str: ...
    def _check_key_exists(self, key: str) -> bool: ...
    def _store_key(self, key: str) -> None: ...
    def get_unique_key(self) -> Optional[str]: ...