"""Add config column to User table

Revision ID: c3ec5c89cb7c
Revises: a7c2bb23148a
Create Date: 2023-04-08 04:50:38.485251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ec5c89cb7c'
down_revision = 'a7c2bb23148a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
