import numpy as np

government_types = {
  'Democracy': {
        'description': 'A system of government by the whole population, typically through elected representatives.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.9,
            'Security': 0.7,
            'Rule of Law': 0.9,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.3,
            'Democracy': 1.0,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.9,
            'Privacy': 0.7,
            'Civic Participation': 0.9,
            'Diplomatic': 0.8,
            'Isolationism': 0.2,
            'Nationalism': 0.5,
            'Militaristic': 0.5,
            'Economic Control': 0.4,
            'Open Borders': 0.6,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.9,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.8,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.4,
            'Technological Integration': 0.8,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.3,
            'State Intervention': 0.5,
            'Economic Equality': 0.5,
            'Autarky': 0.2,
            'Merit-based Advancement': 0.8,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.4,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.6
        }
    },
    'Oligarchy': {
        'description': 'A small group of people having control of a country or organization.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.4,
            'Security': 0.8,
            'Rule of Law': 0.6,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.3,
            'Social Welfare': 0.5,
            'Social Mobility': 0.3,
            'Centralization': 0.8,
            'Democracy': 0.2,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.4,
            'Privacy': 0.5,
            'Civic Participation': 0.3,
            'Diplomatic': 0.7,
            'Isolationism': 0.4,
            'Nationalism': 0.6,
            'Militaristic': 0.6,
            'Economic Control': 0.7,
            'Open Borders': 0.3,
            'Education System': 0.6,
            'Healthcare System': 0.5,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.3,
            'Press Freedom': 0.3,
            'Innovation and Research': 0.6,
            'State Religion': 0.4,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.3,
            'Class Stratification': 0.8,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.6,
            'Economic Equality': 0.2,
            'Autarky': 0.3,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.2,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.2,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.3
        }
    },
    'Monarchy': {
        'description': 'A form of government with a monarch at the head.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.6,
            'Security': 0.8,
            'Rule of Law': 0.7,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.5,
            'Political Freedom': 0.4,
            'Social Welfare': 0.6,
            'Social Mobility': 0.4,
            'Centralization': 0.9,
            'Democracy': 0.1,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.5,
            'Privacy': 0.6,
            'Civic Participation': 0.4,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.7,
            'Militaristic': 0.7,
            'Economic Control': 0.5,
            'Open Borders': 0.4,
            'Education System': 0.7,
            'Healthcare System': 0.6,
            'Property Ownership': 0.8,
            'Freedom of Assembly': 0.5,
            'Press Freedom': 0.4,
            'Innovation and Research': 0.5,
            'State Religion': 0.8,
            'Compulsory Military Service': 0.5,
            'Egalitarianism': 0.4,
            'Class Stratification': 0.7,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.1,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.5,
            'Economic Equality': 0.3,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.3,
            'Historical Continuity': 0.9,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.2,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.4
        }
    },
    'Dictatorship': {
        'description': 'Government by a dictator.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.2,
            'Security': 0.9,
            'Rule of Law': 0.4,
            'Gender Equality': 0.3,
            'Religious Tolerance': 0.4,
            'Political Freedom': 0.1,
            'Social Welfare': 0.6,
            'Social Mobility': 0.2,
            'Centralization': 1.0,
            'Democracy': 0,
            'Environmental Sustainability': 0.4,
            'Information Freedom': 0.1,
            'Privacy': 0.2,
            'Civic Participation': 0.1,
            'Diplomatic': 0.5,
            'Isolationism': 0.5,
            'Nationalism': 0.8,
            'Militaristic': 0.9,
            'Economic Control': 0.8,
            'Open Borders': 0.1,
            'Education System': 0.5,
            'Healthcare System': 0.5,
            'Property Ownership': 0.4,
            'Freedom of Assembly': 0.1,
            'Press Freedom': 0.1,
            'Innovation and Research': 0.5,
            'State Religion': 0.5,
            'Compulsory Military Service': 0.7,
            'Egalitarianism': 0.2,
            'Class Stratification': 0.8,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.1,
            'Worker Self-Management': 0.1,
            'State Intervention': 0.9,
            'Economic Equality': 0.2,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.3,
            'Innovation Encouragement': 0.4,
            'Public Commons': 0.2,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.9,
            'Participatory Governance': 0,
            'Sustainability Focus': 0.3,
            'Global Solidarity': 0.2
        }
    },
    'Anarchy': {
        'description': 'A state of disorder due to absence or nonrecognition of authority.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.8,
            'Security': 0.2,
            'Rule of Law': 0.1,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.9,
            'Political Freedom': 1.0,
            'Social Welfare': 0.4,
            'Social Mobility': 0.8,
            'Centralization': 0,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 1.0,
            'Privacy': 0.9,
            'Civic Participation': 1.0,
            'Diplomatic': 0.2,
            'Isolationism': 0.7,
            'Nationalism': 0.1,
            'Militaristic': 0.1,
            'Economic Control': 0.1,
            'Open Borders': 0.9,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 1.0,
            'Press Freedom': 1.0,
            'Innovation and Research': 0.8,
            'State Religion': 0,
            'Compulsory Military Service': 0,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.1,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.7,
            'Worker Self-Management': 0.9,
            'State Intervention': 0,
            'Economic Equality': 0.8,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.9,
            'Public Commons': 0.9,
            'Historical Continuity': 0.3,
            'Ideological Enforcement': 0,
            'Participatory Governance': 1.0,
            'Sustainability Focus': 0.9,
            'Global Solidarity': 0.8
        }
    },
    'Theocracy': {
        'description': 'A system of government in which priests rule in the name of God or a god.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.3,
            'Security': 0.7,
            'Rule of Law': 0.6,
            'Gender Equality': 0.4,
            'Religious Tolerance': 0.1,
            'Political Freedom': 0.2,
            'Social Welfare': 0.6,
            'Social Mobility': 0.3,
            'Centralization': 0.9,
            'Democracy': 0.1,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.2,
            'Privacy': 0.3,
            'Civic Participation': 0.2,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.6,
            'Militaristic': 0.6,
            'Economic Control': 0.6,
            'Open Borders': 0.2,
            'Education System': 0.6,
            'Healthcare System': 0.6,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.2,
            'Press Freedom': 0.2,
            'Innovation and Research': 0.4,
            'State Religion': 1.0,
            'Compulsory Military Service': 0.5,
            'Egalitarianism': 0.3,
            'Class Stratification': 0.7,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.8,
            'Economic Equality': 0.4,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.4,
            'Innovation Encouragement': 0.3,
            'Public Commons': 0.4,
            'Historical Continuity': 0.8,
            'Ideological Enforcement': 1.0,
            'Participatory Governance': 0.1,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.3
        }
    },
    'Technocracy': {
        'description': 'The government or control of society or industry by an elite of technical experts.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.7,
            'Security': 0.8,
            'Rule of Law': 0.8,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.6,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.7,
            'Democracy': 0.5,
            'Environmental Sustainability': 0.9,
            'Information Freedom': 0.7,
            'Privacy': 0.6,
            'Civic Participation': 0.5,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.5,
            'Economic Control': 0.7,
            'Open Borders': 0.5,
            'Education System': 0.9,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.6,
            'Press Freedom': 0.7,
            'Innovation and Research': 1.0,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.6,
            'Class Stratification': 0.5,
            'Technological Integration': 1.0,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.7,
            'Economic Equality': 0.5,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.9,
            'Innovation Encouragement': 1.0,
            'Public Commons': 0.5,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.6,
            'Sustainability Focus': 0.9,
            'Global Solidarity': 0.5
        }
    },
    'Meritocracy': {
        'description': 'Government or the holding of power by people selected on the basis of their ability.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.8,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.7,
            'Social Mobility': 0.9,
            'Centralization': 0.5,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.7,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.9,
            'Healthcare System': 0.8,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.9,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.8,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.5,
            'State Intervention': 0.6,
            'Economic Equality': 0.6,
            'Autarky': 0.3,
            'Merit-based Advancement': 1.0,
            'Innovation Encouragement': 0.9,
            'Public Commons': 0.4,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.7,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.6
        }
    },
   'Feudal System': {
        'description': 'The social system in medieval Europe, in which the nobility held lands from the Crown in exchange for military service.',
        'category': 'Medieval',
        'prob': {
            'Rights': 0.3,
            'Security': 0.7,
            'Rule of Law': 0.5,
            'Gender Equality': 0.2,
            'Religious Tolerance': 0.4,
            'Political Freedom': 0.2,
            'Social Welfare': 0.4,
            'Social Mobility': 0.2,
            'Centralization': 0.6,
            'Democracy': 0,
            'Environmental Sustainability': 0.4,
            'Information Freedom': 0.2,
            'Privacy': 0.3,
            'Civic Participation': 0.1,
            'Diplomatic': 0.4,
            'Isolationism': 0.5,
            'Nationalism': 0.4,
            'Militaristic': 0.8,
            'Economic Control': 0.7,
            'Open Borders': 0.2,
            'Education System': 0.3,
            'Healthcare System': 0.3,
            'Property Ownership': 0.8,
            'Freedom of Assembly': 0.2,
            'Press Freedom': 0.1,
            'Innovation and Research': 0.3,
            'State Religion': 0.7,
            'Compulsory Military Service': 0.9,
            'Egalitarianism': 0.1,
            'Class Stratification': 1.0,
            'Technological Integration': 0.2,
            'Collective Ownership': 0.1,
            'Worker Self-Management': 0.1,
            'State Intervention': 0.5,
            'Economic Equality': 0.1,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.2,
            'Innovation Encouragement': 0.2,
            'Public Commons': 0.3,
            'Historical Continuity': 0.8,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.1,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.2
        }
    },
    'Empire': {
        'description': 'An extensive group of states or countries ruled over by a single monarch, an oligarchy, or a sovereign state.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.4,
            'Security': 0.9,
            'Rule of Law': 0.6,
            'Gender Equality': 0.3,
            'Religious Tolerance': 0.5,
            'Political Freedom': 0.3,
            'Social Welfare': 0.6,
            'Social Mobility': 0.2,
            'Centralization': 0.9,
            'Democracy': 0.1,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.3,
            'Privacy': 0.4,
            'Civic Participation': 0.2,
            'Diplomatic': 0.8,
            'Isolationism': 0.3,
            'Nationalism': 0.7,
            'Militaristic': 0.9,
            'Economic Control': 0.8,
            'Open Borders': 0.2,
            'Education System': 0.5,
            'Healthcare System': 0.5,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.2,
            'Press Freedom': 0.2,
            'Innovation and Research': 0.4,
            'State Religion': 0.8,
            'Compulsory Military Service': 0.8,
            'Egalitarianism': 0.2,
            'Class Stratification': 0.9,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.1,
            'Worker Self-Management': 0.1,
            'State Intervention': 0.7,
            'Economic Equality': 0.2,
            'Autarky': 0.7,
            'Merit-based Advancement': 0.3,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.2,
            'Historical Continuity': 0.9,
            'Ideological Enforcement': 0.7,
            'Participatory Governance': 0.1,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.4
        }
    },
   'Republic': {
        'description': 'A state in which supreme power is held by the people and their elected representatives, and which has an elected or nominated president rather than a monarch.',
        'category': 'Classical',
        'prob': {
            'Rights': 0.8,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.6,
            'Social Mobility': 0.7,
            'Centralization': 0.5,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.7,
            'Privacy': 0.6,
            'Civic Participation': 0.7,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.6,
            'Militaristic': 0.5,
            'Economic Control': 0.5,
            'Open Borders': 0.5,
            'Education System': 0.7,
            'Healthcare System': 0.6,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.7,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.6,
            'Class Stratification': 0.4,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.3,
            'State Intervention': 0.5,
            'Economic Equality': 0.5,
            'Autarky': 0.3,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.4,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.7,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.5
        }
    },
    'Confederation': {
        'description': 'An organization that consists of a number of parties or groups united in an alliance or league.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.7,
            'Security': 0.6,
            'Rule of Law': 0.7,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.5,
            'Social Mobility': 0.6,
            'Centralization': 0.2,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.4,
            'Militaristic': 0.4,
            'Economic Control': 0.4,
            'Open Borders': 0.7,
            'Education System': 0.6,
            'Healthcare System': 0.6,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.3,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.4,
            'Economic Equality': 0.6,
            'Autarky': 0.2,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.5,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.7
        }
    },
    'Corporate State': {
        'description': 'A state in which corporations play a significant role in government and politics.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.6,
            'Security': 0.7,
            'Rule of Law': 0.6,
            'Gender Equality': 0.6,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.5,
            'Social Welfare': 0.5,
            'Social Mobility': 0.5,
            'Centralization': 0.6,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.5,
            'Privacy': 0.4,
            'Civic Participation': 0.5,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.5,
            'Militaristic': 0.5,
            'Economic Control': 0.7,
            'Open Borders': 0.5,
            'Education System': 0.5,
            'Healthcare System': 0.5,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.4,
            'Press Freedom': 0.4,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.5,
            'Class Stratification': 0.6,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.3,
            'State Intervention': 0.7,
            'Economic Equality': 0.3,
            'Autarky': 0.3,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.3,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.4
        }
    },
   'Tribalism': {
        'description': 'The state or fact of being organized in a tribe or tribes.',
        'category': 'Tribal',
        'prob': {
            'Rights': 0.7,
            'Security': 0.6,
            'Rule of Law': 0.5,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.6,
            'Social Welfare': 0.7,
            'Social Mobility': 0.6,
            'Centralization': 0.2,
            'Democracy': 0.5,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.5,
            'Privacy': 0.6,
            'Civic Participation': 0.8,
            'Diplomatic': 0.3,
            'Isolationism': 0.5,
            'Nationalism': 0.7,
            'Militaristic': 0.4,
            'Economic Control': 0.3,
            'Open Borders': 0.4,
            'Education System': 0.4,
            'Healthcare System': 0.6,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.4,
            'Innovation and Research': 0.3,
            'State Religion': 0.4,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.2,
            'Technological Integration': 0.3,
            'Collective Ownership': 0.8,
            'Worker Self-Management': 0.7,
            'State Intervention': 0.2,
            'Economic Equality': 0.7,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.3,
            'Public Commons': 0.8,
            'Historical Continuity': 0.9,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.7,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.4
        }
    },
    'Matriarchy': {
        'description': 'A system of society or government ruled by a woman or women.',
        'category': 'Tribal',
        'prob': {
            'Rights': 0.8,
            'Security': 0.6,
            'Rule of Law': 0.6,
            'Gender Equality': 1.0,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.4,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.7,
            'Privacy': 0.8,
            'Civic Participation': 0.8,
            'Diplomatic': 0.5,
            'Isolationism': 0.4,
            'Nationalism': 0.5,
            'Militaristic': 0.3,
            'Economic Control': 0.4,
            'Open Borders': 0.6,
            'Education System': 0.7,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.6,
            'State Religion': 0.5,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.3,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.7,
            'Worker Self-Management': 0.7,
            'State Intervention': 0.5,
            'Economic Equality': 0.8,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.8,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.7,
            'Historical Continuity': 0.7,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.6
        }
    },
    'Patriarchy': {
        'description': 'A system of society or government in which men hold the power and women are largely excluded from it.',
        'category': 'Tribal',
        'prob': {
            'Rights': 0.6,
            'Security': 0.7,
            'Rule of Law': 0.6,
            'Gender Equality': 0.2,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.6,
            'Social Welfare': 0.7,
            'Social Mobility': 0.6,
            'Centralization': 0.5,
            'Democracy': 0.5,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.6,
            'Privacy': 0.5,
            'Civic Participation': 0.5,
            'Diplomatic': 0.6,
            'Isolationism': 0.5,
            'Nationalism': 0.7,
            'Militaristic': 0.6,
            'Economic Control': 0.6,
            'Open Borders': 0.4,
            'Education System': 0.6,
            'Healthcare System': 0.7,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.6,
            'Press Freedom': 0.6,
            'Innovation and Research': 0.6,
            'State Religion': 0.6,
            'Compulsory Military Service': 0.5,
            'Egalitarianism': 0.3,
            'Class Stratification': 0.6,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.4,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.6,
            'Economic Equality': 0.5,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.5,
            'Historical Continuity': 0.7,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.5
        }
    },
    'Cyberocracy': {
        'description': 'A proposed form of government that rules by the effective use of information.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.8,
            'Security': 0.8,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.7,
            'Social Mobility': 0.7,
            'Centralization': 0.6,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.9,
            'Privacy': 0.9,
            'Civic Participation': 0.7,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.5,
            'Economic Control': 0.5,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.9,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.4,
            'Technological Integration': 1.0,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.5,
            'State Intervention': 0.6,
            'Economic Equality': 0.6,
            'Autarky': 0.3,
            'Merit-based Advancement': 0.8,
            'Innovation Encouragement': 1.0,
            'Public Commons': 0.6,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.7
        }
    },
    'Eco-Governance': {
        'description': 'Governance by ecological principles to manage human impact on the environment.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.8,
            'Security': 0.7,
            'Rule of Law': 0.7,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.5,
            'Democracy': 0.7,
            'Environmental Sustainability': 1.0,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.9,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.8,
            'Collective Ownership': 0.6,
            'Worker Self-Management': 0.6,
            'State Intervention': 0.6,
            'Economic Equality': 0.7,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.9,
            'Public Commons': 0.9,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 1.0,
            'Global Solidarity': 0.7
        }
    },
    'Direct Democracy': {
        'description': 'A form of democracy in which people decide on policy initiatives directly.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.9,
            'Security': 0.6,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.9,
            'Social Welfare': 0.7,
            'Social Mobility': 0.7,
            'Centralization': 0.2,
            'Democracy': 1.0,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.9,
            'Privacy': 0.8,
            'Civic Participation': 1.0,
            'Diplomatic': 0.6,
            'Isolationism': 0.3,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.4,
            'Worker Self-Management': 0.5,
            'State Intervention': 0.4,
            'Economic Equality': 0.7,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.7,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 1.0,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.6
        }
    },
   'Plutocracy': {
        'description': 'Government by the wealthy.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.5,
            'Security': 0.7,
            'Rule of Law': 0.6,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.4,
            'Social Welfare': 0.4,
            'Social Mobility': 0.3,
            'Centralization': 0.6,
            'Democracy': 0.2,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.5,
            'Privacy': 0.4,
            'Civic Participation': 0.3,
            'Diplomatic': 0.5,
            'Isolationism': 0.5,
            'Nationalism': 0.6,
            'Militaristic': 0.6,
            'Economic Control': 0.9,
            'Open Borders': 0.4,
            'Education System': 0.6,
            'Healthcare System': 0.5,
            'Property Ownership': 0.9,
            'Freedom of Assembly': 0.4,
            'Press Freedom': 0.4,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.2,
            'Class Stratification': 0.9,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.5,
            'Economic Equality': 0.1,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.3,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.2,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.3
        }
    },
    'Syndicalism': {
        'description': 'A movement for transferring the ownership and control of the means of production and distribution to workers\' unions.',
        'category': 'Industrial',
        'prob': {
            'Rights': 0.8,
            'Security': 0.6,
            'Rule of Law': 0.7,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.7,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.3,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.7,
            'Privacy': 0.6,
            'Civic Participation': 0.8,
            'Diplomatic': 0.5,
            'Isolationism': 0.4,
            'Nationalism': 0.5,
            'Militaristic': 0.3,
            'Economic Control': 0.3,
            'Open Borders': 0.5,
            'Education System': 0.7,
            'Healthcare System': 0.8,
            'Property Ownership': 0.3,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.2,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.9,
            'State Intervention': 0.4,
            'Economic Equality': 0.9,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.8,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.7
        }
    },
    'Communism': {
        'description': 'A political theory derived from Karl Marx, advocating class war and leading to a society in which all property is publicly owned and each person works and is paid according to their abilities and needs.',
        'category': 'Modern',
        'prob': {
            'Rights': 0.4,
            'Security': 0.7,
            'Rule of Law': 0.5,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.4,
            'Political Freedom': 0.3,
            'Social Welfare': 0.9,
            'Social Mobility': 0.8,
            'Centralization': 0.9,
            'Democracy': 0.2,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.3,
            'Privacy': 0.3,
            'Civic Participation': 0.4,
            'Diplomatic': 0.5,
            'Isolationism': 0.5,
            'Nationalism': 0.5,
            'Militaristic': 0.6,
            'Economic Control': 0.9,
            'Open Borders': 0.2,
            'Education System': 0.8,
            'Healthcare System': 0.9,
            'Property Ownership': 0.1,
            'Freedom of Assembly': 0.3,
            'Press Freedom': 0.2,
            'Innovation and Research': 0.6,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.6,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.1,
            'Technological Integration': 0.6,
            'Collective Ownership': 1.0,
            'Worker Self-Management': 0.7,
            'State Intervention': 1.0,
            'Economic Equality': 0.9,
            'Autarky': 0.7,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.9,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.8,
            'Participatory Governance': 0.3,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.6
        }
    },
    'Participatory Democracy': {
        'description': 'Emphasis on the broad participation of constituents in the direction and operation of political systems.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.8,
            'Social Mobility': 0.8,
            'Centralization': 0.2,
            'Democracy': 1.0,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.9,
            'Privacy': 0.8,
            'Civic Participation': 1.0,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.5,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.8,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.4,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.5,
            'Worker Self-Management': 0.7,
            'State Intervention': 0.4,
            'Economic Equality': 0.7,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.7,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 1.0,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.7
        }
    },
    'Gerontocracy': {
        'description': 'Government by the elderly.',
        'prob': {
            'Rights': 0.6,
            'Security': 0.7,
            'Rule of Law': 0.7,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.5,
            'Social Welfare': 0.8,
            'Social Mobility': 0.4,
            'Centralization': 0.6,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.6,
            'Privacy': 0.6,
            'Civic Participation': 0.5,
            'Diplomatic': 0.6,
            'Isolationism': 0.5,
            'Nationalism': 0.6,
            'Militaristic': 0.4,
            'Economic Control': 0.5,
            'Open Borders': 0.4,
            'Education System': 0.6,
            'Healthcare System': 0.8,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.5,
            'Press Freedom': 0.5,
            'Innovation and Research': 0.4,
            'State Religion': 0.6,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.5,
            'Class Stratification': 0.5,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.6,
            'Economic Equality': 0.5,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.4,
            'Public Commons': 0.5,
            'Historical Continuity': 0.8,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.5
        }
    },
    'Stratocracy': {
        'description': 'Government by the military.',
        'prob': {
            'Rights': 0.4,
            'Security': 0.9,
            'Rule of Law': 0.6,
            'Gender Equality': 0.4,
            'Religious Tolerance': 0.5,
            'Political Freedom': 0.3,
            'Social Welfare': 0.5,
            'Social Mobility': 0.3,
            'Centralization': 0.8,
            'Democracy': 0.2,
            'Environmental Sustainability': 0.4,
            'Information Freedom': 0.3,
            'Privacy': 0.3,
            'Civic Participation': 0.2,
            'Diplomatic': 0.5,
            'Isolationism': 0.6,
            'Nationalism': 0.8,
            'Militaristic': 1.0,
            'Economic Control': 0.6,
            'Open Borders': 0.2,
            'Education System': 0.5,
            'Healthcare System': 0.5,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.2,
            'Press Freedom': 0.2,
            'Innovation and Research': 0.5,
            'State Religion': 0.4,
            'Compulsory Military Service': 0.9,
            'Egalitarianism': 0.3,
            'Class Stratification': 0.6,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.7,
            'Economic Equality': 0.4,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.3,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.7,
            'Participatory Governance': 0.1,
            'Sustainability Focus': 0.3,
            'Global Solidarity': 0.4
        }
    },
    'Timocracy': {
        'description': 'A form of government in which possession of property is required in order to hold office.',
        'prob': {
            'Rights': 0.6,
            'Security': 0.7,
            'Rule of Law': 0.7,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.5,
            'Social Welfare': 0.5,
            'Social Mobility': 0.4,
            'Centralization': 0.5,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.5,
            'Privacy': 0.5,
            'Civic Participation': 0.5,
            'Diplomatic': 0.6,
            'Isolationism': 0.5,
            'Nationalism': 0.6,
            'Militaristic': 0.5,
            'Economic Control': 0.6,
            'Open Borders': 0.4,
            'Education System': 0.6,
            'Healthcare System': 0.6,
            'Property Ownership': 0.8,
            'Freedom of Assembly': 0.6,
            'Press Freedom': 0.5,
            'Innovation and Research': 0.6,
            'State Religion': 0.5,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.4,
            'Class Stratification': 0.7,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.5,
            'Economic Equality': 0.4,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.4,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.5
        }
    },
    'Nomocracy': {
        'description': 'The rule of law by which all persons, institutions, and entities are accountable.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.7,
            'Rule of Law': 1.0,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.6,
            'Social Mobility': 0.6,
            'Centralization': 0.4,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.7,
            'Diplomatic': 0.6,
            'Isolationism': 0.3,
            'Nationalism': 0.5,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.7,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.7,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.4,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.5,
            'State Intervention': 0.5,
            'Economic Equality': 0.6,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.5,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.7,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.6
        }
    },
    'Kratocracy': {
        'description': 'Government by those who are strong enough to seize power through force or cunning.',
        'prob': {
            'Rights': 0.3,
            'Security': 0.8,
            'Rule of Law': 0.4,
            'Gender Equality': 0.4,
            'Religious Tolerance': 0.4,
            'Political Freedom': 0.3,
            'Social Welfare': 0.4,
            'Social Mobility': 0.3,
            'Centralization': 0.7,
            'Democracy': 0.2,
            'Environmental Sustainability': 0.3,
            'Information Freedom': 0.3,
            'Privacy': 0.3,
            'Civic Participation': 0.2,
            'Diplomatic': 0.4,
            'Isolationism': 0.6,
            'Nationalism': 0.7,
            'Militaristic': 0.9,
            'Economic Control': 0.7,
            'Open Borders': 0.2,
            'Education System': 0.4,
            'Healthcare System': 0.4,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.2,
            'Press Freedom': 0.2,
            'Innovation and Research': 0.4,
            'State Religion': 0.5,
            'Compulsory Military Service': 0.8,
            'Egalitarianism': 0.2,
            'Class Stratification': 0.8,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.2,
            'Worker Self-Management': 0.2,
            'State Intervention': 0.8,
            'Economic Equality': 0.3,
            'Autarky': 0.7,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.3,
            'Public Commons': 0.2,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.8,
            'Participatory Governance': 0.1,
            'Sustainability Focus': 0.3,
            'Global Solidarity': 0.3
        }
    },
    'Ochlocracy': {
        'description': 'Mob rule, government by mob or a mass of people.',
        'prob': {
            'Rights': 0.5,
            'Security': 0.4,
            'Rule of Law': 0.3,
            'Gender Equality': 0.5,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.6,
            'Social Welfare': 0.5,
            'Social Mobility': 0.5,
            'Centralization': 0.2,
            'Democracy': 0.5,
            'Environmental Sustainability': 0.4,
            'Information Freedom': 0.6,
            'Privacy': 0.5,
            'Civic Participation': 0.7,
            'Diplomatic': 0.3,
            'Isolationism': 0.5,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.4,
            'Open Borders': 0.5,
            'Education System': 0.5,
            'Healthcare System': 0.5,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.7,
            'Press Freedom': 0.6,
            'Innovation and Research': 0.5,
            'State Religion': 0.4,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.6,
            'Class Stratification': 0.5,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.4,
            'Worker Self-Management': 0.5,
            'State Intervention': 0.4,
            'Economic Equality': 0.5,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.5,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.6,
            'Sustainability Focus': 0.4,
            'Global Solidarity': 0.4
        }
    },
    'Kritarchy': {
        'description': 'Government by judges.',
        'prob': {
            'Rights': 0.7,
            'Security': 0.7,
            'Rule of Law': 0.9,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.6,
            'Social Welfare': 0.6,
            'Social Mobility': 0.6,
            'Centralization': 0.5,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.7,
            'Privacy': 0.7,
            'Civic Participation': 0.6,
            'Diplomatic': 0.5,
            'Isolationism': 0.4,
            'Nationalism': 0.5,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.7,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.7,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.4,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.3,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.6,
            'Economic Equality': 0.6,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.5,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.5,
            'Participatory Governance': 0.5,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.5
        }
    },
    'Panarchism': {
        'description': 'Government by all forms of rule, chosen by individuals.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.6,
            'Rule of Law': 0.7,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.7,
            'Social Mobility': 0.8,
            'Centralization': 0.2,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.9,
            'Privacy': 0.8,
            'Civic Participation': 0.9,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.8,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.8,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.8,
            'Collective Ownership': 0.5,
            'Worker Self-Management': 0.7,
            'State Intervention': 0.4,
            'Economic Equality': 0.7,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.7,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.8
        }
    },
    'Sortition': {
        'description': 'The action of selecting or determining something by the drawing of lots.',
        'prob': {
            'Rights': 0.7,
            'Security': 0.6,
            'Rule of Law': 0.7,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.7,
            'Social Welfare': 0.6,
            'Social Mobility': 0.6,
            'Centralization': 0.4,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.7,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.6,
            'Isolationism': 0.5,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.5,
            'Open Borders': 0.6,
            'Education System': 0.7,
            'Healthcare System': 0.6,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.7,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.7,
            'Class Stratification': 0.5,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.4,
            'Worker Self-Management': 0.6,
            'State Intervention': 0.5,
            'Economic Equality': 0.6,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.6,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.7,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.6
        }
    },
    'Band Society': {
        'description': 'The simplest form of human society, characterized by a lack of hierarchical leadership.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.6,
            'Rule of Law': 0.5,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.7,
            'Social Mobility': 0.8,
            'Centralization': 0.1,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.8,
            'Privacy': 0.8,
            'Civic Participation': 0.8,
            'Diplomatic': 0.4,
            'Isolationism': 0.4,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.3,
            'Open Borders': 0.8,
            'Education System': 0.5,
            'Healthcare System': 0.7,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.5,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.2,
            'Technological Integration': 0.4,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.9,
            'State Intervention': 0.2,
            'Economic Equality': 0.8,
            'Autarky': 0.7,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.9,
            'Historical Continuity': 0.8,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.7
        }
    },
    'Chiefdom': {
        'description': 'Political organization with a chief at the head.',
        'prob': {
            'Rights': 0.6,
            'Security': 0.7,
            'Rule of Law': 0.6,
            'Gender Equality': 0.6,
            'Religious Tolerance': 0.7,
            'Political Freedom': 0.5,
            'Social Welfare': 0.6,
            'Social Mobility': 0.5,
            'Centralization': 0.7,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.6,
            'Privacy': 0.6,
            'Civic Participation': 0.6,
            'Diplomatic': 0.5,
            'Isolationism': 0.5,
            'Nationalism': 0.6,
            'Militaristic': 0.5,
            'Economic Control': 0.6,
            'Open Borders': 0.5,
            'Education System': 0.6,
            'Healthcare System': 0.6,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.5,
            'Press Freedom': 0.5,
            'Innovation and Research': 0.5,
            'State Religion': 0.7,
            'Compulsory Military Service': 0.5,
            'Egalitarianism': 0.5,
            'Class Stratification': 0.7,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.5,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.6,
            'Economic Equality': 0.5,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.5,
            'Public Commons': 0.6,
            'Historical Continuity': 0.7,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.5
        }
    },    
    'Non-state Societies': {
        'description': 'Complex societies that do not fit the state model, often highlighted for their horizontal social structures.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.5,
            'Rule of Law': 0.4,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.7,
            'Social Mobility': 0.8,
            'Centralization': 0.1,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.9,
            'Diplomatic': 0.4,
            'Isolationism': 0.4,
            'Nationalism': 0.3,
            'Militaristic': 0.2,
            'Economic Control': 0.3,
            'Open Borders': 0.7,
            'Education System': 0.6,
            'Healthcare System': 0.7,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.2,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.9,
            'State Intervention': 0.2,
            'Economic Equality': 0.8,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.9,
            'Historical Continuity': 0.7,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.9,
            'Global Solidarity': 0.8
        }
    },
    'Gift Economy': {
        'description': 'Economic system in which goods and services are given without a direct agreement for immediate or future rewards.',
        'prob': {
            'Rights': 0.7,
            'Security': 0.6,
            'Rule of Law': 0.5,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.2,
            'Democracy': 0.6,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.7,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.5,
            'Isolationism': 0.5,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.2,
            'Open Borders': 0.7,
            'Education System': 0.6,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.7,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.1,
            'Technological Integration': 0.5,
            'Collective Ownership': 0.8,
            'Worker Self-Management': 0.8,
            'State Intervention': 0.1,
            'Economic Equality': 0.9,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.9,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.7
        }
    },
    'Mutual Aid Society': {
        'description': 'System where groups of individuals work together for common or mutually beneficial goals.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.6,
            'Rule of Law': 0.6,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.9,
            'Social Mobility': 0.8,
            'Centralization': 0.2,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.8,
            'Privacy': 0.8,
            'Civic Participation': 0.9,
            'Diplomatic': 0.5,
            'Isolationism': 0.4,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.3,
            'Open Borders': 0.7,
            'Education System': 0.7,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.7,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.2,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.9,
            'State Intervention': 0.2,
            'Economic Equality': 0.9,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.9,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.8
        }
    },
    'Consociationalism': {
        'description': 'A form of government involving guaranteed group representation.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.8,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.3,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.8,
            'Privacy': 0.8,
            'Civic Participation': 0.9,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.4,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.3,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.5,
            'Worker Self-Management': 0.6,
            'State Intervention': 0.5,
            'Economic Equality': 0.7,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.7,
            'Historical Continuity': 0.6,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.7
        }
    },
    'Bioregionalism': {
        'description': 'Governance based on ecological or natural borders rather than political ones.',
        'prob': {
            'Rights': 0.8,
            'Security': 0.6,
            'Rule of Law': 0.7,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.7,
            'Social Mobility': 0.7,
            'Centralization': 0.3,
            'Democracy': 0.7,
            'Environmental Sustainability': 1.0,
            'Information Freedom': 0.8,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.3,
            'Militaristic': 0.3,
            'Economic Control': 0.4,
            'Open Borders': 0.7,
            'Education System': 0.7,
            'Healthcare System': 0.7,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.7,
            'Worker Self-Management': 0.7,
            'State Intervention': 0.4,
            'Economic Equality': 0.7,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.9,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 1.0,
            'Global Solidarity': 0.7
        }
    },
    'Digital Democracy': {
        'description': 'Use of information and communication technology to promote democracy.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.8,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.9,
            'Social Welfare': 0.7,
            'Social Mobility': 0.7,
            'Centralization': 0.4,
            'Democracy': 0.9,
            'Environmental Sustainability': 0.6,
            'Information Freedom': 0.9,
            'Privacy': 0.7,
            'Civic Participation': 0.9,
            'Diplomatic': 0.7,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.5,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.7,
            'Property Ownership': 0.7,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.8,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.9,
            'Collective Ownership': 0.5,
            'Worker Self-Management': 0.6,
            'State Intervention': 0.4,
            'Economic Equality': 0.7,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.8,
            'Innovation Encouragement': 0.9,
            'Public Commons': 0.7,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.6,
            'Global Solidarity': 0.7
        }
    },
    'Egalitarianism': {
        'description': 'A form of society or government based on the principle of equality.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.7,
            'Rule of Law': 0.8,
            'Gender Equality': 0.9,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.8,
            'Social Welfare': 0.8,
            'Social Mobility': 0.8,
            'Centralization': 0.3,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.8,
            'Privacy': 0.8,
            'Civic Participation': 0.9,
            'Diplomatic': 0.6,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.3,
            'Economic Control': 0.4,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.7,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.2,
            'Egalitarianism': 1.0,
            'Class Stratification': 0.1,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.7,
            'Worker Self-Management': 0.8,
            'State Intervention': 0.5,
            'Economic Equality': 0.9,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.8,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.3,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.8
        }
    },
    'State Capitalism': {
        'description': 'A political system in which the state has control of production and the use of capital.',
        'prob': {
            'Rights': 0.6,
            'Security': 0.8,
            'Rule of Law': 0.7,
            'Gender Equality': 0.6,
            'Religious Tolerance': 0.6,
            'Political Freedom': 0.5,
            'Social Welfare': 0.7,
            'Social Mobility': 0.5,
            'Centralization': 0.8,
            'Democracy': 0.4,
            'Environmental Sustainability': 0.5,
            'Information Freedom': 0.5,
            'Privacy': 0.5,
            'Civic Participation': 0.5,
            'Diplomatic': 0.6,
            'Isolationism': 0.5,
            'Nationalism': 0.6,
            'Militaristic': 0.6,
            'Economic Control': 0.9,
            'Open Borders': 0.4,
            'Education System': 0.7,
            'Healthcare System': 0.7,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.5,
            'Press Freedom': 0.5,
            'Innovation and Research': 0.6,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.5,
            'Egalitarianism': 0.5,
            'Class Stratification': 0.6,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.8,
            'Worker Self-Management': 0.4,
            'State Intervention': 0.9,
            'Economic Equality': 0.6,
            'Autarky': 0.6,
            'Merit-based Advancement': 0.5,
            'Innovation Encouragement': 0.6,
            'Public Commons': 0.4,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.6,
            'Participatory Governance': 0.4,
            'Sustainability Focus': 0.5,
            'Global Solidarity': 0.5
        }
    },    
    'Market Socialism': {
        'description': 'An economic system in which there is a market economy directed and regulated by the state but operated by cooperatives.',
        'prob': {
            'Rights': 0.7,
            'Security': 0.7,
            'Rule of Law': 0.7,
            'Gender Equality': 0.7,
            'Religious Tolerance': 0.8,
            'Political Freedom': 0.7,
            'Social Welfare': 0.8,
            'Social Mobility': 0.7,
            'Centralization': 0.5,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.7,
            'Information Freedom': 0.7,
            'Privacy': 0.7,
            'Civic Participation': 0.8,
            'Diplomatic': 0.6,
            'Isolationism': 0.4,
            'Nationalism': 0.5,
            'Militaristic': 0.4,
            'Economic Control': 0.7,
            'Open Borders': 0.6,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.6,
            'Freedom of Assembly': 0.8,
            'Press Freedom': 0.8,
            'Innovation and Research': 0.7,
            'State Religion': 0.3,
            'Compulsory Military Service': 0.4,
            'Egalitarianism': 0.8,
            'Class Stratification': 0.3,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.8,
            'State Intervention': 0.7,
            'Economic Equality': 0.8,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.8,
            'Historical Continuity': 0.5,
            'Ideological Enforcement': 0.4,
            'Participatory Governance': 0.8,
            'Sustainability Focus': 0.7,
            'Global Solidarity': 0.7
        }
    },
    'Libertarian Socialism': {
        'description': 'A political philosophy that advocates for the abolition of the state and the establishment of a society based on voluntary associations and cooperative ownership of the means of production.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.6,
            'Rule of Law': 0.6,
            'Gender Equality': 0.9,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.7,
            'Social Mobility': 0.8,
            'Centralization': 0.1,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.9,
            'Privacy': 0.9,
            'Civic Participation': 0.9,
            'Diplomatic': 0.5,
            'Isolationism': 0.3,
            'Nationalism': 0.4,
            'Militaristic': 0.2,
            'Economic Control': 0.4,
            'Open Borders': 0.7,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.5,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.8,
            'State Religion': 0.2,
            'Compulsory Military Service': 0.1,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.2,
            'Technological Integration': 0.7,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 0.9,
            'State Intervention': 0.2,
            'Economic Equality': 0.9,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.8,
            'Public Commons': 0.9,
            'Historical Continuity': 0.4,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.8
        }
    },
    'Anarcho-Syndicalism': {
        'description': 'A theory of anarchism that views revolutionary industrial unionism or syndicalism as the method for workers in capitalist society to gain control of an economy.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.5,
            'Rule of Law': 0.5,
            'Gender Equality': 0.9,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.8,
            'Social Mobility': 0.8,
            'Centralization': 0.2,
            'Democracy': 0.7,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.9,
            'Privacy': 0.9,
            'Civic Participation': 0.9,
            'Diplomatic': 0.4,
            'Isolationism': 0.3,
            'Nationalism': 0.3,
            'Militaristic': 0.2,
            'Economic Control': 0.3,
            'Open Borders': 0.7,
            'Education System': 0.7,
            'Healthcare System': 0.8,
            'Property Ownership': 0.4,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.7,
            'State Religion': 0.1,
            'Compulsory Military Service': 0.1,
            'Egalitarianism': 0.9,
            'Class Stratification': 0.1,
            'Technological Integration': 0.6,
            'Collective Ownership': 0.9,
            'Worker Self-Management': 1.0,
            'State Intervention': 0.2,
            'Economic Equality': 0.9,
            'Autarky': 0.4,
            'Merit-based Advancement': 0.6,
            'Innovation Encouragement': 0.7,
            'Public Commons': 0.9,
            'Historical Continuity': 0.3,
            'Ideological Enforcement': 0.2,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.8
        }
    },
    'Anarcho-Communism': {
        'description': 'A theory of anarchism which advocates the abolition of the state, private property, and capitalism in favor of common ownership of the means of production.',
        'prob': {
            'Rights': 0.9,
            'Security': 0.4,
            'Rule of Law': 0.4,
            'Gender Equality': 0.9,
            'Religious Tolerance': 0.9,
            'Political Freedom': 0.9,
            'Social Welfare': 0.8,
            'Social Mobility': 0.8,
            'Centralization': 0.1,
            'Democracy': 0.8,
            'Environmental Sustainability': 0.8,
            'Information Freedom': 0.9,
            'Privacy': 0.9,
            'Civic Participation': 0.9,
            'Diplomatic': 0.3,
            'Isolationism': 0.2,
            'Nationalism': 0.2,
            'Militaristic': 0.1,
            'Economic Control': 0.2,
            'Open Borders': 0.8,
            'Education System': 0.8,
            'Healthcare System': 0.8,
            'Property Ownership': 0.1,
            'Freedom of Assembly': 0.9,
            'Press Freedom': 0.9,
            'Innovation and Research': 0.7,
            'State Religion': 0.1,
            'Compulsory Military Service': 0.0,
            'Egalitarianism': 1.0,
            'Class Stratification': 0.0,
            'Technological Integration': 0.6,
            'Collective Ownership': 1.0,
            'Worker Self-Management': 1.0,
            'State Intervention': 0.1,
            'Economic Equality': 1.0,
            'Autarky': 0.5,
            'Merit-based Advancement': 0.7,
            'Innovation Encouragement': 0.7,
            'Public Commons': 1.0,
            'Historical Continuity': 0.2,
            'Ideological Enforcement': 0.1,
            'Participatory Governance': 0.9,
            'Sustainability Focus': 0.8,
            'Global Solidarity': 0.9
        }
    },
    "Council Communism": {
      "description": "A form of communism led by workers councils as opposed to a party-led state.",
      "prob": {
        "Rights": 0.8,
        "Security": 0.5,
        "Rule of Law": 0.6,
        "Gender Equality": 0.8,
        "Religious Tolerance": 0.8,
        "Political Freedom": 0.7,
        "Social Welfare": 0.9,
        "Social Mobility": 0.7,
        "Centralization": 0.3,
        "Democracy": 0.8,
        "Environmental Sustainability": 0.7,
        "Information Freedom": 0.8,
        "Privacy": 0.7,
        "Civic Participation": 0.9,
        "Diplomatic": 0.5,
        "Isolationism": 0.4,
        "Nationalism": 0.3,
        "Militaristic": 0.3,
        "Economic Control": 0.7,
        "Open Borders": 0.6,
        "Education System": 0.8,
        "Healthcare System": 0.9,
        "Property Ownership": 0.4,
        "Freedom of Assembly": 0.8,
        "Press Freedom": 0.8,
        "Innovation and Research": 0.6,
        "State Religion": 0.2,
        "Compulsory Military Service": 0.2,
        "Egalitarianism": 0.9,
        "Class Stratification": 0.2,
        "Technological Integration": 0.5,
        "Collective Ownership": 0.9,
        "Worker Self-Management": 1.0,
        "State Intervention": 0.6,
        "Economic Equality": 0.9,
        "Autarky": 0.5,
        "Merit-based Advancement": 0.5,
        "Innovation Encouragement": 0.6,
        "Public Commons": 0.9,
        "Historical Continuity": 0.3,
        "Ideological Enforcement": 0.4,
        "Participatory Governance": 0.9,
        "Sustainability Focus": 0.7,
        "Global Solidarity": 0.7
      }
    },
    "Anarcho-Primitivism": {
      "description": "An anarchist critique of the origins and progress of civilization, advocating a return to pre-industrial societies.",
      "prob": {
        "Rights": 0.9,
        "Security": 0.4,
        "Rule of Law": 0.4,
        "Gender Equality": 0.9,
        "Religious Tolerance": 0.9,
        "Political Freedom": 0.9,
        "Social Welfare": 0.6,
        "Social Mobility": 0.6,
        "Centralization": 0.1,
        "Democracy": 0.7,
        "Environmental Sustainability": 0.9,
        "Information Freedom": 0.8,
        "Privacy": 0.9,
        "Civic Participation": 0.9,
        "Diplomatic": 0.3,
        "Isolationism": 0.7,
        "Nationalism": 0.2,
        "Militaristic": 0.2,
        "Economic Control": 0.2,
        "Open Borders": 0.8,
        "Education System": 0.5,
        "Healthcare System": 0.5,
        "Property Ownership": 0.5,
        "Freedom of Assembly": 0.9,
        "Press Freedom": 0.8,
        "Innovation and Research": 0.4,
        "State Religion": 0.2,
        "Compulsory Military Service": 0.1,
        "Egalitarianism": 0.9,
        "Class Stratification": 0.1,
        "Technological Integration": 0.2,
        "Collective Ownership": 0.9,
        "Worker Self-Management": 0.9,
        "State Intervention": 0.1,
        "Economic Equality": 0.8,
        "Autarky": 0.9,
        "Merit-based Advancement": 0.6,
        "Innovation Encouragement": 0.3,
        "Public Commons": 0.9,
        "Historical Continuity": 0.9,
        "Ideological Enforcement": 0.1,
        "Participatory Governance": 0.8,
        "Sustainability Focus": 0.9,
        "Global Solidarity": 0.6
      }
    },
    "Communalism": {
      "description": "A political system where local councils form the basis of governance, operating on principles of direct democracy, from the bottom up, often emphasizing ecological and communal living.",
      "prob": {
        "Rights": 0.8,
        "Security": 0.6,
        "Rule of Law": 0.7,
        "Gender Equality": 0.8,
        "Religious Tolerance": 0.8,
        "Political Freedom": 0.8,
        "Social Welfare": 0.8,
        "Social Mobility": 0.7,
        "Centralization": 0.2,
        "Democracy": 0.9,
        "Environmental Sustainability": 0.9,
        "Information Freedom": 0.8,
        "Privacy": 0.8,
        "Civic Participation": 0.9,
        "Diplomatic": 0.5,
        "Isolationism": 0.3,
        "Nationalism": 0.4,
        "Militaristic": 0.2,
        "Economic Control": 0.4,
        "Open Borders": 0.7,
        "Education System": 0.7,
        "Healthcare System": 0.8,
        "Property Ownership": 0.6,
        "Freedom of Assembly": 0.9,
        "Press Freedom": 0.9,
        "Innovation and Research": 0.7,
        "State Religion": 0.2,
        "Compulsory Military Service": 0.2,
        "Egalitarianism": 0.9,
        "Class Stratification": 0.2,
        "Technological Integration": 0.6,
        "Collective Ownership": 0.9,
        "Worker Self-Management": 0.9,
        "State Intervention": 0.3,
        "Economic Equality": 0.8,
        "Autarky": 0.5,
        "Merit-based Advancement": 0.7,
        "Innovation Encouragement": 0.7,
        "Public Commons": 0.9,
        "Historical Continuity": 0.4,
        "Ideological Enforcement": 0.3,
        "Participatory Governance": 0.9,
        "Sustainability Focus": 0.9,
        "Global Solidarity": 0.7
      }
    }
  }


# Function to calculate the similarity score between actual dimensions and expected dimensions for each governance type
def calculate_similarity(gov_type, actual_dimensions):
    similarity_score = 0
    for dimension, value in actual_dimensions.items():
        expected_value = gov_type.get(dimension, 0)  # Default to 0 if dimension not found
        similarity_score += (1 - abs(expected_value - value))  # Higher score for closer match
    return similarity_score

# Function to determine governance type based on dimensions
def determine_governance_type(dimensions):
    max_score = -np.inf
    best_fit_gov_type = None
    for gov_type, properties in government_types.items():
        print(properties)
        score = calculate_similarity(properties['prob'], dimensions)
        if score > max_score:
            max_score = score
            best_fit_gov_type = gov_type
    return best_fit_gov_type
